spring.application.name=Pro3SemesterAssignmentPart2

#db.url=jdbc:postgresql://localhost:5432/db
#db.user=admin
#db.password=admin

#updated to use Springboot
spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect